### ISSUE TITLE
Max upload file size of 2mb!

### ISSUE THREAD

**Issue by farshidhss** [visiblevc/wordpress-starter#160] opened 2019-10-20 11:52 UTC
The first thing I do in wordpress is to upload a file but this image only has maximum file size upload for wordpress set to 2mb! Do I need to mount the config to fix it?

**Comment by signaleleven** [comment] 2019-10-21 07:58
I appreciate that you edited the test to be less snarky :D 
I mount a custom `php.ini` config to override that setting. An alternative would be to build an image based on wordpress-starter with the changes you need in php.ini

**Comment by farshidhss** [comment] 2019-10-21 08:30
It is certainly better to be less snarky :D 
I will mount the php.ini then, as I don't feel comfortable to touch the docker file. Would be nice if you give some explanation on what the docker file is doing on a high level.

**Comment by dsifford** [comment] 2019-10-21 15:14
Checked into it and it looks like WPEngine and a couple other popular WordPress providers use a default of 50mb for max upload size. So I'll consider bumping it to that. If that sounds acceptable.

Agree that 2mb is not quite enough, but I haven't personally needed it.

**Comment by farshidhss** [comment] 2019-10-21 15:18
> Checked into it and it looks like WPEngine and a couple other popular WordPress providers use a default of 50mb for max upload size. So I'll consider bumping it to that. If that sounds acceptable.
> 
> Agree that 2mb is not quite enough, but I haven't personally needed it.

It would help a lot if this already included a large max file upload size. My workflow is that I often setup a fresh Wordpress and then use wp-migration to import a large existing Wordpress into the local setup. This makes it very easy to make quick improvements without actually messing with a live website.

**Comment by dsifford** [comment] 2019-10-21 15:28
If that's the case, why not just use wp-cli as described in the readme?

You can import a mysql dump or a WXR file, which would arguably be easier than doing it using the frontend interface because it could be automated on build.

**Comment by farshidhss** [comment] 2019-10-21 15:31
> If that's the case, why not just use wp-cli as described in the readme?
> 
> You can import a mysql dump or a WXR file, which would arguably be easier than doing it using the frontend interface because it could be automated on build.

With wp-migration I can import database, templates, and all uploaded files at the same time. It is very smooth process and takes just a few seconds to get the entire website ready to go. I have never seen another simpler method. This takes basically one click to download the exported file and then one click to import everything and it always worked for all websites that I worked on.

**Comment by dsifford** [comment] 2019-10-21 15:47
I should also note that by default, if you have a database export mounted into `/data/*.sql`, it'll automatically get imported on build using our orchestration we set up.

**Comment by farshidhss** [comment] 2019-10-26 09:56
> Yep, same with either of the two methods I described.
> 
> I do it using the [sqldump method](https://github.com/visiblevc/wordpress-starter#working-with-databases) and mounting the `wp-content/uploads` directory.
> 
> But if using WXR is your preferred method (which I assume is what wp-migration does), you can achieve the same thing there using wp-cli's [`wp import`](https://developer.wordpress.org/cli/commands/import/) command.

I don't think wp-migration plugin is creating a WRX format and hence not importable. I even tried to import it using the instructions in the readme and it failed. I see that the command in your instruction is wrong:
npm run wp db import /data/database.sql

This won't work even if I just wanted to import a sql database because it would not be able to find the file. I tried it already. 

Even if all the above could work magically, I would still have to solve the problem of replacing the domain name with localhost:8080 which adds another unnecessary step.
All in all, I tried and wasted a lot of time on this. As I said the workflow of exporting using wp-migration always proved to be the simplest for me and I wished you could at least see the point that it would save people time and make your image more useful but maybe you prefer your ways. It's a pity. I move on.

**Comment by dsifford** [comment] 2019-10-26 14:33
> `docker-compose exec wordpress bash "db" "import" "backup-20191014-061359-540.wpress"`

If this is what the readme says, it's incorrect.. It needs to be...

```sh
$ docker-compose exec wordpress wp db import <your-sql-export.sql>
#                     ^^^^^^^^^ name of wordpress service in docker-compose.yml
#                               ^^ command to run
#                                  ^^^^^^^^^ subcommand
#                                            ^^^^^^^^^^^^^^^^^^^^^ an exported sql file
```

> Even if all the above could work magically,

It does, I can assure you that.

> I would still have to solve the problem of replacing the domain name with localhost:8080 which adds another unnecessary step. 

Adding a [`URL_REPLACE`](https://github.com/visiblevc/wordpress-starter#wordpress) env variable literally does exactly that.

> Yes, the instructions says I have to modify the docker-compose and add it there but I don't see why when a simple wp-migration plugin solves it all!?

Because if you add that single line to the `docker-compose.yml` file, and follow the rest of the instructions, the import process is 100% fully automated and you don't have to do anything at all, rather than having to export and import a site manually.

> All in all, I tried and wasted a lot of time on this. As I said the workflow of exporting using wp-migration always proved to be the simplest for me and I wished you could at least see the point that it would save people time and make your image more useful.

The method you describe is **objectively not more useful or simpler**. The issue is solely due to the fact that you failed to read and understand the instructions we've written in the readme. Your method would not save people any time. It is not faster. It is not easier.

I agree that it is probably best that you move on.

**Comment by farshidhss** [comment] 2019-10-26 14:36
![image](https://user-images.githubusercontent.com/4727688/67621217-a00dcb80-f80e-11e9-92f2-e5f6af9b7803.png)
This is the screenshot of your readme. I simply followed what it says.

**Closed** 2019-11-15 18:58 UTC
