### ISSUE TITLE
Pruning themes and plugins is overzealous

### ISSUE THREAD

**Issue by kitwestneat** [visiblevc/wordpress-starter#51] opened 2016-10-28 14:34 UTC
Change 8a10e7a557e03d1c44da9ee799a1985a7e7ee369 made it so any themes and plugins not defined in the (optional) variables THEMES and PLUGINS variables are deleted. This makes working on local themes and plugins difficult, though it appears that there is a new undocumented [local] tag that one can use to whitelist local plugins.

Since THEMES and PLUGINS are optional, it seems like it'd be better to skip pruning if those variables are not defined. Alternatively, it'd be nice if themes and plugins that are already active in the database restore were not pruned. Thanks.

**Comment by karellm** [comment] 2016-10-28 15:07
@dsifford I think I agree with that. I got confused too the first time I ran the new build that my local theme got deleted.

@kitwestneat In the meantime, you can simply list your plugins by name in the `docker-compose.yml`. This will keep them from being deleted.

**Comment by dsifford** [comment] 2016-10-28 15:46
I had a feeling there'd be some pushback on this

> new undocumented [local] tag

This isn't documented? That should definitely be fixed. 

> Since THEMES and PLUGINS are optional, it seems like it'd be better to skip pruning if those variables are not defined.

I still think there's merit in pruning `hello` and `akismet`. I often require a clean environment when testing plugins.

> Alternatively, it'd be nice if themes and plugins that are already active in the database restore were not pruned.

This is "possible", but will be difficult to pull off. Execution of this would require doing `wp plugin list`, returning json, iterating through and pulling out all plugins that are listed as "active" and then operating on that list. Not sure it's worth the effort

**Comment by karellm** [comment] 2016-10-28 16:19
I second deleting default themes and plugins but since this list is known and rarely changing (once a year), we could whitelist the plugins/themes we delete rather than trying to be smart about what is in the project. It used to be like that before. We just loop the 4 default themes and 2 default plugins and unless there are active, we prune them. We never prune anything else.

Instead of `wp plugin list` we could use [status](http://wp-cli.org/commands/plugin/status/) before pruning the theme. It is a little easier I think.

**Comment by dsifford** [comment] 2016-10-28 16:49
Sounds good to me. Can you take care of making the switch @karellm? I've got some other priorities I've got to get finished over the next couple of days.

**Comment by karellm** [comment] 2016-10-28 17:39
I will try to tackle it next week.

**Comment by dsifford** [comment] 2016-10-30 18:29
@karellm Came across this today, which may be relevant for this: https://github.com/billerickson/wp-cli-plugin-install-missing

**Comment by andrewhavens** [comment] 2017-04-20 05:31
Why not put this behind an ENV var feature flag? That way, you could enable the "auto-prune" by setting to true but it would default to false. As a newcomer, it was a little scary when the theme that I was developing was automatically deleted from my computer before I had committed the changes to version control. Luckily, I had a backup, but the auto-prune was definitely an unexpected behavior. I even had the theme name listed in my docker-compose config. However, I did not know to mark it as `[local]` which is why it was deleted. The auto-prune seems like a nice feature, but it seems like it should be an opt-in sort of feature to prevent mistakes.

**Comment by karellm** [comment] 2017-04-20 13:23
@andrewhavens I think it should be removed altogether. I don't have the bandwidth to do that now but a PR is welcome. Or maybe @dsifford can take a look at it?

**Comment by dsifford** [comment] 2017-04-20 14:02
I still think there's merit in pruning automatically @karellm. I think you were onto something when you suggested using `wp plugin status` rather than `list`, but I still haven't had the time to dig into it.

Maybe this weekend.

**Closed** 2017-05-23 16:06 UTC
