### ISSUE TITLE
Documentation for automatical deploy

### ISSUE THREAD

**Issue by lukasholzer** [visiblevc/wordpress-starter#115] opened 2017-09-26 14:04 UTC
Can you write the documentation for **automatical deploy for production** in the Readme.md?
It would be nice to see how you suggest a production workflow with this loved repo.

Regards Lukas

**Comment by karellm** [comment] 2017-10-02 15:45
Closing as duplicate of #118

**Closed by karellm** 2017-10-02 15:45 UTC
